### ISSUE TITLE
Touch input not working on Windows

### ISSUE THREAD

**Issue by asallay** [vladikoff/chromeos-apk#23]
Touch screen input not working on Surface Pro.
Mouse input seems to work fine.
Multiple users reported problems with this device.

Using Chrome 37 64bit, but the problem is irrelevant to the version.

**Comment by lonku** [comment]
same issue with the Acer Iconia w4

**Comment by larbis** [comment]
I have tried to run Android apk on Win7/8 and Linux ubuntu 12.04. Unfortunately, I fail on all of environments.  More specifically, the touch function didn't work at all.

I wonder which cause this problem. Is it OS or device?
Is there any OS or device which works touch function? If it is, what is the OS/version or device name?

**Comment by TheWraithL98** [comment]
@vladikoff did you ever get anywhere with geting touch to work on the HP Stream 7?     I was maintaining hope for this project, but I am thinking of buying AMIDUOS instead.

**Comment by wokawoka** [comment]
having the touchscreen working would be a real game changer... Still no updates about it?

**Comment by duron23** [comment]
Any update on this, and how to fix it :(

**Comment by rocketinventor** [comment]
I also had this problem on my dell venue 8 pro with windows 8.1
Everything else worked with touch, even regular desktop apps.

**Comment by chicato83** [comment]
@vladikoff are you still working on fix it. what you need for fix this issue.

**Comment by duron23** [comment]
Hi any update on this ??

**Comment by DC-Graphics** [comment]
Please give update! Still not fixed!

**Comment by siliconglen** [comment]
Me too. Chrome 44.0.2403.130  on Windows 10 home. Didn't have this issue with Windows 7. Samsung laptop

**Comment by rocketinventor** [comment]
@siliconglen All devices that support touch events will likely not work for touch. Windows 7 probably works because it just uses an invisible mouse cursor.

**Comment by neeradkumar** [comment]
Waiting for an update :)

**Comment by siliconglen** [comment]
I'm not seeing the bug anymore, is it fixed?

**Comment by DC-Graphics** [comment]
it is fixed for me

siliconglen <notifications@github.com> schrieb am Mi., 21. Okt. 2015 um
23:05 Uhr:

**Comment by mmm286** [comment]
Is fixed???? When?

**Comment by siliconglen** [comment]
I'm using a Samsung touch screen laptop with Windows 10 Home. Chrome 46.0.2490.71 m
I've overridding the chrome://flags Enable Touch Events setting and it is set to Enabled.

Everything seems to work fine from a touchscreen point of view such as google maps zooming, web scrolling  and zooming etc  The angry birds chrome link given earlier no longer works as it has been discontinued

I'm not sure if the touch events would still work if I put the flag back to automatic. Would be good to hear from others where it is working what setting they have for this.

Craig

**Comment by angel12** [comment]
Still not working for me, Windows 10, touch set to enabled, using a new install of archon just downloaded from the website

**Comment by neeradkumar** [comment]
Doesn't work for me. Enabled touch events. HP touch smart, Windows 10, chrome 46.0.2490.71 m

**Comment by gbraad** [comment]
Windows 10 on Yoga S3 and Thinkpad 10 have the same issues. Touch events and stylus input (Wacom) do not register correctly. Only mouse input seems to work.

**Comment by HDaddict** [comment]
Also following this issue.

I'm using it on a Cube i7 Stylus tablet, and touch support is lacking. I tried enabling touch events, but it doesn't work.

Is there any progress with this issue @vladikoff 

Keep up the great work

**Comment by HDaddict** [comment]
UPDATE:
I confirm that touch works with **ARC WELDER **and the** built in ARC** with Chrome Version 49.0.2623.64 beta-m (64-bit).

Touch DOES NOT WORK with ARChon.

It turns out I installed both ARC welder and ARChon at first, so that's why touch didn't work for me.

**Comment by rocketinventor** [comment]
@HDaddict So, in other words, Google fixed the problem but in ARC but, this fork, archon has still not implemented it?

**Comment by HDaddict** [comment]
@rocketinventor It looks so... As I noted stylus input works, but somehow touch doesn't work.

**Comment by rocketinventor** [comment]
@HDaddict That's probably because it is just emulating a standard pointer device

**Comment by hltdev8642** [comment]
weird thing, but I noticed stylus scrolls lists and other touch events when holding down the left click button. try using some sort of key mapping program maybe to set it to be held down constantly in chrome converted app only or something...
